# Generated by Django 4.2.7 on 2026-03-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название подразделения', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительское подразделение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.department')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='ФИО сотрудника', max_length=200)),
                ('position', models.CharField(help_text='Должность', max_length=200)),
                ('hired_at', models.DateField(blank=True, help_text='Дата найма (опционально)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи')),
                ('department', models.ForeignKey(help_text='Подразделение сотрудника', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.department')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_department_name_per_parent'),
        ),
    ]
